name: CI/CD

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: false # Change to true if you want to push the image to a registry
        tags: pr-${{ github.event.pull_request.number }}

  deploy:
    if: github.event.pull_request.merged == true
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Deploy container
      run: |
        docker run -d -p 5000:5000 pr-${{ github.event.pull_request.number }}
    
  cleanup:
    if: github.event.pull_request.closed == true && github.event.pull_request.merged == false
    runs-on: ubuntu-latest

    steps:
    - name: Cleanup container
      run: |
        docker stop pr-${{ github.event.pull_request.number }} && docker rm pr-${{ github.event.pull_request.number }}
